### ISSUE TITLE
想问一下老哥怎么测试通过

### ISSUE THREAD

**Issue by loser-wang** [razertory/MIT6.824-Java#6]
老哥用java实现，怎么验证模块是否正确

**Comment by razertory** [comment]
现阶段实现还不完整。对应的测试，会考虑用 shell 脚本去实现。类似 https://pdos.csail.mit.edu/6.824/schedule.html

**Comment by razertory** [comment]
> 老哥用java实现，怎么验证模块是否正确

目前，MapReduce 完成了，为了方便大家测试。测试用例统一在测试代码当中 https://github.com/razertory/MIT6.824-Java/blob/main/mapreduce/src/test/java/MRWordCountTest.java
